# PostgreSQL. Versions 9.5 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/opt/homebrew/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: meu_portfolio_development

 

  <<: *default
  database: meu_portfolio_test

#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Connection URLs for non-primary databases can also be configured using
# environment variables. The variable name is formed by concatenating the
# connection name with `_DATABASE_URL`. For example:
#
#   CACHE_DATABASE_URL="postgres://cacheuser:cachepass@localhost/cachedatabase"
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cable:
    <<: *primary_production